### PR TITLE
Remove discrete from Y_actual, YA_actual and YB_actual

### PR DESCRIPTION
**Pull request by christiankral**
I suppose the `discrete` shall be removed from the variables

- `Y_actual`
- `YA_actual`
- `YB_actual`

as they are not set in a when clause but simply in the in two different if branches in the equation section

### CODE REVIEW

**Comment by christiankral** [comment]
The `when` is closer to the physical model as the affected variables definitely behave like discrete variables. I am not sure if this is a sufficient indicator for better numerical behavior.

**Comment by casella** [comment]
@kabdelhak, @AnHeuermann, what do you think?

**Comment by AnHeuermann** [comment]
I'm not sure what we are doing exactly with discrete variables inside the runtime. E.g. for FMI there is a function to update discrete variables which is usually (always?) called after events. I think we are doing the same for the standard C runtime.
You can try it out and have a close look directly at event time and the first step after.

Could `Y_actual ` become eventually a state? Then I assume `reinit()` should be the better option. But honestly I'm not a modeller.

**Comment by AnHeuermann** [comment]
So I think there should be no big difference in
```
discrete Real Y_actual;
when breakerStatus == BreakersState.Bc then
    Y_actual = Yseries;
```
and
```
Real Y_actual;
if breakerStatus == BreakersState.Bc then
    reinit(Y_actual, Yseries);
```
from a numerical point of view, as long `Y_actual` is a state.

**Pull request merged**
