### PR TITLE
Removed unnecessary duplicate definitions

### PR DESCRIPTION
**Pull request by casella**
Removed unecessary duplicated definition of UStart, which is already in the base class and gives trouble with current OMEdit (see [#5788](https://trac.openmodelica.org/OpenModelica/ticket/5788)). Also removed unnecessary parameter thetaStart, since UPhaseStart from the base class should have been used instead, that has the same meaning.

@adriguir,  this change is strictly speaking non-backwards compatible, but it should be not a problem since most users will keep the default value of zero for the reference bus voltage. I think it's best to clean up the code now before the library has many users, rather than adding some ugly hacks to guarantee 100% backward compatibility with some design mistakes at such an early stage of development.

### CODE REVIEW

**Comment by adriguir** [comment]
I'm in phase with your comments: better now than later

**Comment by casella** [comment]
I think there is another such change that may not really be 100% backwards compatible but should be implemented ASAP. I already discussed this with @AndreaBartolini.

For transmission line models, that only have one nominal voltage, we introduced `UNom` and made `UNomA` and `UNomB` final. In retrospect, this is really not a good idea, because it breaks plug compatibility. A transmission line model _is a_ PartialTwoPortAC, and as such you should still be able to change UNomA and UNomB.

I'll take care of that ASAP.

**Comment by adriguir** [comment]
From a data model point of view, it would be better to do the modifications you suggest.

However, from a modeling point of view, a transmission line should have the same nominal voltages. Otherwise, it is a transformer. Considering this, I would suggest to have an assert for the lines checking that UNomA and UNomB are identical, what do you think?

**Comment by casella** [comment]
> However, from a modeling point of view, a transmission line should have the same nominal voltages. Otherwise, it is a transformer. Considering this, I would suggest to have an assert for the lines checking that UNomA and UNomB are identical, what do you think?

Sounds good. The question is what we do with UNom. If we remove it, we break all the existing line models around, which is definitely not good. My plan was to keep it and then basically remove the final modifier from UNomA and UNomB, so that they could still (in principle) be modified when instantiating. 

Of course I can add an assert. Checking for equality with Reals is verboten, I guess we should check they are less than 5% different. Which could also be the case for long distribution lines with significant resistance, though it wouldn't make much sense to use two different nominal values.

What do you think?

**Comment by adriguir** [comment]
It sounds good for me.

**Pull request merged**
